project:
  type: book

book:
  title: "R basics for Research"
  author: "Marcelino Guerra"
  date: "8/16/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - start.qmd
    - datai.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
